services: 
  converter:
    build: 
      context: ./converter
      dockerfile: Dockerfile

  redis:
    image: redis:alpine3.20
    command: redis-server --notify-keyspace-events AKE

  logstash:
    profiles: ["exclude"]
    image: logstash:8.10.2
    depends_on:
      - elasticsearch
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf 

  elasticsearch:
    profiles: ["exclude"]
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      # Пока не будем беспокоиться о безопасности
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./deploy/esdata:/usr/share/elasticsearch/data

  kibana:
    profiles: ["exclude"]
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
